// Edit product details here. Images are relative to index.html.
const products = [
  {
    "cat": "Women",
    "type": "Sarees",
    "id": "women-sarees",
    "name": "Kanchi Cotton Saree – Coffee Brown",
    "price": 1100,
    "old": 1500,
    "tag": "Offer",
    "sizes": "Confirm on WhatsApp",
    "img": "images/catalog/kanchi-cotton-coffee-brown.jpeg",
    "supplied": true
  },
  {
    "cat": "Women",
    "type": "Kurtis",
    "id": "women-kurtis",
    "name": "Noor Embroidered Kurti",
    "price": 749,
    "old": 1049,
    "tag": "Trending",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-kurtis.webp"
  },
  {
    "cat": "Women",
    "type": "Churidars",
    "id": "women-churidars",
    "name": "Jasmine Churidar Set",
    "price": 1099,
    "old": 1399,
    "tag": "New Arrivals",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-churidars.webp"
  },
  {
    "cat": "Women",
    "type": "Salwar Suits",
    "id": "women-salwar-suits",
    "name": "Vanya Ethnic Salwar Set",
    "price": 1099,
    "old": 1399,
    "tag": "Best Seller",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-salwar-suits.webp"
  },
  {
    "cat": "Women",
    "type": "Anarkali Dresses",
    "id": "women-anarkali-dresses",
    "name": "Meher Floral Anarkali",
    "price": 1199,
    "old": 1499,
    "tag": "New Arrivals",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-anarkali-dresses.webp"
  },
  {
    "cat": "Women",
    "type": "Gowns",
    "id": "women-gowns",
    "name": "Ira Evening Gown",
    "price": 1499,
    "old": 1799,
    "tag": "New Arrivals",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-gowns.webp"
  },
  {
    "cat": "Women",
    "type": "Tops",
    "id": "women-tops",
    "name": "Everyday Cotton Top",
    "price": 599,
    "old": 899,
    "tag": "Trending",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-tops.webp"
  },
  {
    "cat": "Women",
    "type": "Leggings",
    "id": "women-leggings",
    "name": "Essential Stretch Leggings",
    "price": 399,
    "old": 699,
    "tag": "Offer",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-leggings.webp"
  },
  {
    "cat": "Women",
    "type": "Nightwear",
    "id": "women-nightwear",
    "name": "Cloud Cotton Nightwear Set",
    "price": 699,
    "old": 999,
    "tag": "Offer",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-nightwear.webp"
  },
  {
    "cat": "Women",
    "type": "Casual Wear",
    "id": "women-casual-wear",
    "name": "Weekend Casual Dress",
    "price": 849,
    "old": 1149,
    "tag": "Trending",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-casual-wear.webp"
  },
  {
    "cat": "Women",
    "type": "Party Wear",
    "id": "women-party-wear",
    "name": "Ruby Celebration Dress",
    "price": 1599,
    "old": 1899,
    "tag": "Offer",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-party-wear.webp"
  },
  {
    "cat": "Women",
    "type": "Ethnic Wear",
    "id": "women-ethnic-wear",
    "name": "Heritage Ethnic Set",
    "price": 1399,
    "old": 1699,
    "tag": "Festival",
    "sizes": "S, M, L, XL",
    "img": "images/catalog/women-ethnic-wear.webp"
  },
  {
    "cat": "Girls",
    "type": "Frocks",
    "id": "girls-frocks",
    "name": "Daisy Cotton Frock",
    "price": 599,
    "old": 899,
    "tag": "New Arrivals",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-frocks.webp"
  },
  {
    "cat": "Girls",
    "type": "Party Frocks",
    "id": "girls-party-frocks",
    "name": "Mithra Party Frock",
    "price": 899,
    "old": 1199,
    "tag": "Offer",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-party-frocks.webp"
  },
  {
    "cat": "Girls",
    "type": "Traditional Dresses",
    "id": "girls-traditional-dresses",
    "name": "Little Lotus Traditional Set",
    "price": 1099,
    "old": 1399,
    "tag": "Festival",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-traditional-dresses.webp"
  },
  {
    "cat": "Girls",
    "type": "Lehenga Choli",
    "id": "girls-lehenga-choli",
    "name": "Aarna Festive Lehenga",
    "price": 999,
    "old": 1299,
    "tag": "Festival",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-lehenga-choli.webp"
  },
  {
    "cat": "Girls",
    "type": "Pattu Pavadai",
    "id": "girls-pattu-pavadai",
    "name": "Nila Pattu Pavadai",
    "price": 1299,
    "old": 1599,
    "tag": "Festival",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-pattu-pavadai.webp"
  },
  {
    "cat": "Girls",
    "type": "Gowns",
    "id": "girls-gowns",
    "name": "Starshine Girls Gown",
    "price": 1199,
    "old": 1499,
    "tag": "Best Seller",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-gowns.webp"
  },
  {
    "cat": "Girls",
    "type": "Tops & Bottom Sets",
    "id": "girls-tops-bottom-sets",
    "name": "Sunny Day Top & Bottom Set",
    "price": 699,
    "old": 999,
    "tag": "Trending",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-tops-bottom-sets.webp"
  },
  {
    "cat": "Girls",
    "type": "Casual Dresses",
    "id": "girls-casual-dresses",
    "name": "Playday Cotton Dress",
    "price": 599,
    "old": 899,
    "tag": "New Arrivals",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-casual-dresses.webp"
  },
  {
    "cat": "Girls",
    "type": "Festive Dresses",
    "id": "girls-festive-dresses",
    "name": "Golden Bloom Festive Dress",
    "price": 1099,
    "old": 1399,
    "tag": "Festival",
    "sizes": "2–10 Years",
    "img": "images/catalog/girls-festive-dresses.webp"
  }
];
